version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgdata-monimes:/var/lib/postgresql/data/pgdata
  web:
    build:
      context: .
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  pgdata-monimes:

