# Generated by Django 3.0.6 on 2021-09-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_item_variation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='apartment_address',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone_number',
            field=models.CharField(default='088454653', max_length=100, verbose_name='Phone'),
            preserve_default=False,
        ),
    ]
